export const MIGRATION_IS_NOT_DONE = "MIGRATION_IS_NOT_DONE";
export const MIGRATE_THIS_VIRTUAL_MANUALLY = "MIGRATE_THIS_VIRTUAL_MANUALLY";
export const THIS_PROPERTY_IS_TOO_DEEP = 'THIS_PROPERTY_IS_TOO_DEEP'